language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
  - "pypy3" # this is 3.6
env:
  - JOB=tests

jobs:
  include:
    - python: "3.8"
      env:
        - JOB=check
    - python: "3.8"
      env:
        - JOB=docs
  allow_failures:
    - python: "nightly"
    - python: "pypy3"
    # added power support arch.
    - python: "3.8"
      env:
        - JOB=check
          arch: ppc64le
    - python: "3.8"
      env:
        - JOB=docs
          arch: ppc64le
  allow_failures:
    - python: "nightly"
    - python: "pypy3"
      arch: ppc64le
install: |
  case $JOB in
    tests) pip install .;;
    docs) pip install .[doc];;
    check) pip install mypy;;
  esac

script: |
  case $JOB in
    tests) python setup.py test;;
    docs) python setup.py build; make -C doc html man;;
    check) mypy --ignore-missing-imports khard;;
  esac
